packages:
  - "@internal/*"
  - "apps/*"
  - "packages/*"

catalog:
  vite: ^6.0.7
  vitest: ^2.1.8
  '@vitest/ui': ^2.1.8
  typescript: ^5.7.2
  unbuild: ^3.2.0
  '@biomejs/biome': ^1.9.4
  lefthook: ^1.10.1
  tailwindcss: ^3.4.17
  postcss: ^8.4.49
  autoprefixer: ^10.4.20
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/node': ^22.10.5
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0 
  nanoid: ^5.0.9
  dayjs: ^1.11.13